== Deployment

The goal is to avoid syntax errors when importing workbench transports, this is done by storing objects from transports and systems in git, then simulating the state after import and then verifying by running link:https://abaplint.org/[abaplint].

The user will not be allowed to release a transport from DEV if it results in syntax errors in QAS. Similariy, the setup will give a list of transports which are good to import into follow-on systems.

The result of this setup are simple lists of good transports, but there are multiple automatic processes running to produce the lists, this chapter describes the proposed setup.

=== Git Mirroring

To support a CD setup, systems are mirrored into a specific CD repository, developers will not be working with this repository, it is only used for automation. In this setup git is used as a filesystem, more than the actual features of git is used.

Transports from DEV are mirrored into branches, the objects of the QAS system is mirroed into a QAS branch and PRE into a PRE branch. PRD is not mirrored, the CD pipeline is executed before PRD.

Developers can use their favorite tooling to do changes in DEV, these changes are reported into transport requests.

[plantuml]
....
skinparam monochrome true

actor Developer

package "Dev Repository" {
  file ""main" branch"as git
}

node DEV
node QAS
node PRE
node PRD

Developer -> DEV
git <-up-> DEV: abapGit

package "CD Repository" {
  file "Transport\nbranches" as UC1
  file ""QAS"\nbranch" as UC2
  file ""PRE"\nbranch" as UC3
}

DEV -> QAS: CTS
QAS -> PRE: CTS
PRE -> PRD: CTS

DEV -down-> UC1: abapGit
QAS -down-> UC2: abapGit
PRE -> UC3: abapGit
....

Below diagram gives an example of the lifecycle for a single transport request "TR1":

[plantuml]
....
skinparam monochrome true

participant Developer
participant DEV
participant QAS
participant PRE
participant PRD
participant Git
participant CI

@startuml
autonumber
Developer -> DEV : Create transport TR1

DEV -> Git : Create branch TR1
DEV -> Git : Push objects to TR1
Git -> CI : Simulate TR1 into QAS

Developer -\\o DEV : Releases TR1
DEV -> QAS : CTS import TR1
note right: Automatic after release
QAS -> Git : Merge TR1 into QAS branch
Git -> CI : Simulate unreleased TRs
QAS -> PRE : CTS queues TR1

Git -> CI : Simulate TR1 into PRE

QAS -\\o PRE : CTS Import TR1
PRE -> Git : Merge TR1 into PRD branch
Git -> CI : Simulate queued PRD TRs

PRE -> PRD : CTS queues TR1

PRE -> PRD : CTS Import TR1
note right: Must follow PRE sequence
@enduml
....

This is the simplest scenario, transport of copies and more system tiers can be added or removed.

=== Maintenance Tasks

Few maintenance tasks to perform regularly,

. Update abapGit on all Systems
. Check QAS and PRD branches are in sync with systems
. Keeping abaplint configuration up to date

=== Prerequsites

. Transports at R3TR level

=== Open Questions

. ABAP Package Checks ?
. Rollback of ABAP objects, abapGit solution, out of this scope?
. SAP notes causing syntax errors in custom code

=== Feasibility

The CD setup will require a lot of jobs to run on the CI servers. This section gives some overall estimates on the number of CI runs given a number of transport requests.

==== Sequential queue clearing

Importing a queue of 10 transport requests, one by one in sequence. Below numbers are for one system, but it must be run for both QAS and PRD in the example landscape.

1. Import TR1, trigger CI on "main", rebase 9 branches
2. Import TR2, trigger CI on "main", rebase 8 branches
3. Import TR3, trigger CI on "main", rebase 7 branches
4. Import TR4, trigger CI on "main", rebase 6 branches
5. Import TR5, trigger CI on "main", rebase 5 branches
6. Import TR6, trigger CI on "main", rebase 4 branches
7. Import TR7, trigger CI on "main", rebase 3 branches
8. Import TR8, trigger CI on "main", rebase 2 branches
9. Import TR9, trigger CI on "main", rebase 1 branches
10. Import TR10, trigger CI on "main"

sequential(10) = 10 + 9 + 8 + 7 + 6 + 5 + 4 + 3 + 2 + 1 = 55

latexmath:[$sequential(n) = \frac{1}{2} n (n+1)$]

https://en.wikipedia.org/wiki/Triangular_number

[width=50%, cols=">1,>1"]
|===
| TRs | CI Runs

| 10 | 55
| 20 | 210
| 50 | 1275
| 100 | 5050
|===

Moving fast in a large SAP installation, having 100 transports per week is relalistic(?)

.Estimate, cost for 5050 CI runs
[cols="1,>1,>1,>1,>1"]
|===
| Scenario       | Time per run | Memory | Price/hour | Total

| Full container | 1 hour       | 256 gb | USD 3.0 | [.underline]#USD 15150#
| abaplint       | 5 minutes    | 8 gb   | USD 0.1 | [.underline]#USD 42#
|===

abaplint 2.74.23, 4 million lines of ABAP and other ABAP artifacts, syntax only, 8 gb memory allocated to node, single core boost = 2.4ghz, in ~10 minutes
(`find -name '*.abap' | xargs cat | wc -l`)

Public link:https://github.com/heliconialabs/abaplint-app-performance[abaplint-app-performance], 500k lines of ABAP in 50 seconds

==== Speculative combinatorics

Example, 3 transports in queue, gives following combinations, note that the sequence is defined by the queue,

[width=50%, cols="1"]
|===
| TR1 TR2 TR3
| TR1 TR2
| TR1 TR3
| TR2 TR3
| TR1
| TR2
| TR3
|===

Binomial cofficient series

latexmath:[$speculative(n) = 2^n - 1$]

https://en.wikipedia.org/wiki/Binomial_coefficient

[width=75%, cols="1,1,1"]
|===
| TRs | Calculation | Result

| 3  TRs |  2^3  - 1 |     7 combinations
| 4  TRs |  2^4  - 1 |    15 combinations
| 10 TRs |  2^10 - 1 |  1023 combinations
|===

Assuming full coverage.

Speculative merge results must be configured for a specific maximum depth.