[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap[https://github.com/heliconialabs/practical-ci-cd-for-abap]

|License
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap/blob/main/LICENSE[Creative Commons]

|Build
|{docdatetime}
|===

== Introduction

ABAP is used for business-critical tasks, basic CI/CD should be the default, not the exception. This document introduces a incremental CI/CD setup releases 702 and up.

abapGit has used abaplint to check for syntax errors before merges for multiple years, a similar but more complex
approach can be used to perform similar checks in a classic SAP landscape where changes are deployed using CTS.

As ABAP is a complicated language, occasionally syntax errors make it into the main branch, the scenario is then fixed in abaplint, and similar errors can henceforth be detected.

=== CTS

Use classic CTS, see link:https://blogs.sap.com/2020/11/05/cts-is-beautiful/[CTS is beautiful] blog

=== Open Source Tooling

Open source tools to encourage an open culture

* link:https://abapgit.org[abapGit]
* link:https://abaplint.org[abaplint]

Delivered independently of the SAP release

The developer can reproduce on local PC

=== CI and CD differences

lorem ipsum

[width=60%, cols="1,1"]
|===
| Continious Integration | Continious Delivery

| Parallel               | Sequential
| Speed                  | Safety
| Flexibility            | Auditability
| Merge                  | Overwrite
| Check Style and Syntax | Syntax Only
| Per every commit       | Transport into system
|===

=== Landscape

The setup will take offset in a classic 4 tier system landscape,

[plantuml]
....
skinparam monochrome true

node DEV
node QAS
node PRE
node PRD

DEV -> QAS
QAS -> PRE
PRE -> PRD
....

`DEV`: Source for all CTS transports

`QAS`: User acceptance test by business users

`PRE`: Important, the development artifacts in this system matches PRD.
Transports are imported to this system just before PRD, in case there is a syntax error the change is abandoned. This will secure no syntax errors in PRD after import.

The scenario can be expanded with more system tiers and transport routes.