[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap[https://github.com/heliconialabs/practical-ci-cd-for-abap]

|License
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap/blob/main/LICENSE[Creative Commons]

|Build
|{docdatetime}
|===

== Introduction

lorem ipsum

* Why is this important?
* benefit everyone, 702 and up
* CTS features is a subset of git??? at least the deployment features?

Securing a PR can be merged safely is much like securing that CTS transprot can be imported safely.

Reproduceable on local PC

Self and independently phased CI/CD rollout and upgrade

=== CTS

classic CTS, see "CTS is beautiful" blog

link:https://blogs.sap.com/2020/11/05/cts-is-beautiful/[CTS is beautiful]

=== Open Source Tooling

Open source tools to encourage an open culture

* link:https://abapgit.org[abapGit]
* link:https://abaplint.org[abaplint]

Delivered independently of the SAP release

=== CI and CD differences

CI = Parallel
CD = Sequential

CI = Speed and flexibility
CD = Safety and auditability

CI = Merge
CD = Overwrite

=== Landscape

The setup described will take offset in a classic 4 tier system landscape,

[plantuml]
....
skinparam monochrome true

node DEV
node QAS
node PRE
node PRD

DEV -> QAS
QAS -> PRE
PRE -> PRD
....

`DEV`: Source for all CTS transports

`QAS`: User acceptance test by business key users

`PRE`: Important, the development artifacts in this system matches PRD.
Transports are imported to this system just before PRD to secure no syntax errors in PRD after import.

The setup can be expanded with more system tiers and transport routes.