[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap[https://github.com/heliconialabs/practical-ci-cd-for-abap]

|License
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap/blob/main/LICENSE[Creative Commons]

|Build
|{docdatetime}
|===

== Introduction

lorem ipsum

* Why is this important?
* benefit everyone, 702 and up
* CTS features is a subset of git??? at least the deployment features?

Securing a PR can be merged safely is much like securing that CTS transprot can be imported safely.

Reproduceable on local PC => incremental cloud style evolution.

Self and independently phased CI/CD rollout and upgrade

=== CTS

classic CTS, see "CTS is beautiful" blog

=== Open Source Tooling

Open source tools to encourage an open culture

abapGit + abaplint

=== CI and CD differences

CI = Parallel
CD = Sequential

CI = Speed and flexibility
CD = Safety and auditability

CI = Merge
CD = Overwrite

=== Landscape

Classic, no new systems, but process can be extended, throwaway systems, distributed development.

[plantuml]
....
skinparam monochrome true

node DEV
node QAS
node PRE
node PRD

DEV -> QAS
QAS -> PRE
PRE -> PRD
....

DEV: Source for all CTS transports

QAS: UAT by business key users

PRE: Important, the development artifacts in this system matches PRD as much as possible.
Transports are imported to this system just before PRD to secure no syntax errors in PRD after import.