[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap[https://github.com/heliconialabs/practical-ci-cd-for-abap]

|License
|link:https://github.com/heliconialabs/practical-ci-cd-for-abap/blob/main/LICENSE[Creative Commons Attribution 4.0 International]

|Build
|{docdatetime}
|===

== Introduction

Basic CI/CD should be the default for ABAP development, not the exception. This document introduces a incremental CI/CD setup for releases 702 and up.

The link:https://abapgit.org[abapGit] project uses link:https://abaplint.org[abaplint] to check for syntax errors before merges, this helps ensuring a stable `main` branch.
A similar, but more complex, approach can be used to perform validations in classic SAP landscapes where changes are deployed using CTS.

As ABAP is a complicated language, occasionally syntax errors make it into the `main` branch, due to missing checks in abaplint. The bug is then fixed in abaplint, and similar errors can henceforth be detected.

=== CTS

CTS will be used for deploying changes between systems in the local landscape.

See the link:https://blogs.sap.com/2020/11/05/cts-is-beautiful/[CTS is beautiful] blog for more insights.

=== Open Source Tooling

The approach is based on open source tooling, this allows developers to share fixes, and promotes an open culture across organizations.

* link:https://abapgit.org[abapGit]
* link:https://abaplint.org[abaplint]

The tooling is delivered independently of SAP releases(702+).

And issues can be reproduced on a local PC by developers, on normal sized hardware.

=== CI and CD differences

The
link:https://www.jetbrains.com/teamcity/ci-cd-guide/continuous-integration-vs-delivery-vs-deployment/[Continuous Integration and Continuous Delivery] terms have different interpretations, but its important to note some of the
conceptual differences:

.CI/CD concepts
[width=70%, cols="1,1"]
|===
| Continuous Integration | Continuous Delivery

| Parallel               | Sequential
| Speed                  | Safety
| Flexibility            | Auditable
| Merge                  | Overwrite
| Style and Syntax       | Syntax Only
| Per commit             | Per build artifact(Transport)
|===

=== Landscape

The setup will take offset in a classic 4 tier system landscape,

[plantuml]
....
skinparam monochrome true

node DEV
node QAS
node PRE
node PRD

DEV -> QAS
QAS -> PRE
PRE -> PRD
....

`DEV`: Source for all CTS transports

`QAS`: User acceptance test by business users

`PRE`: Important, the development artifacts in this system matches PRD.
Transports are imported to this system just before PRD, in case there is a syntax error the change is abandoned. This will secure no syntax errors in PRD after import.

The scenario can be expanded with more system tiers and transport routes.